package hibernate_xml;

// default package
// Generated 31.07.2011 14:20:28 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ItemAttribute generated by hbm2java
 */
public class ItemAttribute implements java.io.Serializable
{

	private long itemAttribute;
	private Long itemAttributeTypeFk;
	private Long itemFk;
	private String typeName;
	private String valueText;
	private BigDecimal valueNumber;
	private Date valueDate;
	private Long dataType;
	private Long orderby;

	public ItemAttribute()
	{
	}

	public ItemAttribute(long itemAttribute)
	{
		this.itemAttribute = itemAttribute;
	}

	public ItemAttribute(long itemAttribute, Long itemAttributeTypeFk, Long itemFk,
			String typeName, String valueText, BigDecimal valueNumber, Date valueDate,
			Long dataType, Long orderby)
	{
		this.itemAttribute = itemAttribute;
		this.itemAttributeTypeFk = itemAttributeTypeFk;
		this.itemFk = itemFk;
		this.typeName = typeName;
		this.valueText = valueText;
		this.valueNumber = valueNumber;
		this.valueDate = valueDate;
		this.dataType = dataType;
		this.orderby = orderby;
	}

	public long getItemAttribute()
	{
		return this.itemAttribute;
	}

	public void setItemAttribute(long itemAttribute)
	{
		this.itemAttribute = itemAttribute;
	}

	public Long getItemAttributeTypeFk()
	{
		return this.itemAttributeTypeFk;
	}

	public void setItemAttributeTypeFk(Long itemAttributeTypeFk)
	{
		this.itemAttributeTypeFk = itemAttributeTypeFk;
	}

	public Long getItemFk()
	{
		return this.itemFk;
	}

	public void setItemFk(Long itemFk)
	{
		this.itemFk = itemFk;
	}

	public String getTypeName()
	{
		return this.typeName;
	}

	public void setTypeName(String typeName)
	{
		this.typeName = typeName;
	}

	public String getValueText()
	{
		return this.valueText;
	}

	public void setValueText(String valueText)
	{
		this.valueText = valueText;
	}

	public BigDecimal getValueNumber()
	{
		return this.valueNumber;
	}

	public void setValueNumber(BigDecimal valueNumber)
	{
		this.valueNumber = valueNumber;
	}

	public Date getValueDate()
	{
		return this.valueDate;
	}

	public void setValueDate(Date valueDate)
	{
		this.valueDate = valueDate;
	}

	public Long getDataType()
	{
		return this.dataType;
	}

	public void setDataType(Long dataType)
	{
		this.dataType = dataType;
	}

	public Long getOrderby()
	{
		return this.orderby;
	}

	public void setOrderby(Long orderby)
	{
		this.orderby = orderby;
	}

}
