package hibernate_xml;

// default package
// Generated 31.07.2011 14:20:28 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ItemPriceList generated by hbm2java
 */
public class ItemPriceList implements java.io.Serializable
{

	private long itemPriceList;
	private Long priceListFk;
	private Long itemFk;
	private Long discountXtra;
	private BigDecimal salePrice;
	private Date created;

	public ItemPriceList()
	{
	}

	public ItemPriceList(long itemPriceList)
	{
		this.itemPriceList = itemPriceList;
	}

	public ItemPriceList(long itemPriceList, Long priceListFk, Long itemFk, Long discountXtra,
			BigDecimal salePrice, Date created)
	{
		this.itemPriceList = itemPriceList;
		this.priceListFk = priceListFk;
		this.itemFk = itemFk;
		this.discountXtra = discountXtra;
		this.salePrice = salePrice;
		this.created = created;
	}

	public long getItemPriceList()
	{
		return this.itemPriceList;
	}

	public void setItemPriceList(long itemPriceList)
	{
		this.itemPriceList = itemPriceList;
	}

	public Long getPriceListFk()
	{
		return this.priceListFk;
	}

	public void setPriceListFk(Long priceListFk)
	{
		this.priceListFk = priceListFk;
	}

	public Long getItemFk()
	{
		return this.itemFk;
	}

	public void setItemFk(Long itemFk)
	{
		this.itemFk = itemFk;
	}

	public Long getDiscountXtra()
	{
		return this.discountXtra;
	}

	public void setDiscountXtra(Long discountXtra)
	{
		this.discountXtra = discountXtra;
	}

	public BigDecimal getSalePrice()
	{
		return this.salePrice;
	}

	public void setSalePrice(BigDecimal salePrice)
	{
		this.salePrice = salePrice;
	}

	public Date getCreated()
	{
		return this.created;
	}

	public void setCreated(Date created)
	{
		this.created = created;
	}

}
