package hibernate_xml;
// Generated 31.07.2011 14:20:28 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ItemAction generated by hbm2java
 */
public class ItemAction implements java.io.Serializable
{

	private long itemAction;
	private Long itemActionTypeFk;
	private Long itemFk;
	private Long storeFromFk;
	private Long storeToFk;
	private Date actionDate;
	private Long createdBy;
	private Long itemCount;
	private BigDecimal actionPrice;
	private String actionNote;
	private Date created;

	public ItemAction()
	{
	}

	public ItemAction(long itemAction)
	{
		this.itemAction = itemAction;
	}

	public ItemAction(long itemAction, Long itemActionTypeFk, Long itemFk, Long storeFromFk,
			Long storeToFk, Date actionDate, Long createdBy, Long itemCount,
			BigDecimal actionPrice, String actionNote, Date created)
	{
		this.itemAction = itemAction;
		this.itemActionTypeFk = itemActionTypeFk;
		this.itemFk = itemFk;
		this.storeFromFk = storeFromFk;
		this.storeToFk = storeToFk;
		this.actionDate = actionDate;
		this.createdBy = createdBy;
		this.itemCount = itemCount;
		this.actionPrice = actionPrice;
		this.actionNote = actionNote;
		this.created = created;
	}

	public long getItemAction()
	{
		return this.itemAction;
	}

	public void setItemAction(long itemAction)
	{
		this.itemAction = itemAction;
	}

	public Long getItemActionTypeFk()
	{
		return this.itemActionTypeFk;
	}

	public void setItemActionTypeFk(Long itemActionTypeFk)
	{
		this.itemActionTypeFk = itemActionTypeFk;
	}

	public Long getItemFk()
	{
		return this.itemFk;
	}

	public void setItemFk(Long itemFk)
	{
		this.itemFk = itemFk;
	}

	public Long getStoreFromFk()
	{
		return this.storeFromFk;
	}

	public void setStoreFromFk(Long storeFromFk)
	{
		this.storeFromFk = storeFromFk;
	}

	public Long getStoreToFk()
	{
		return this.storeToFk;
	}

	public void setStoreToFk(Long storeToFk)
	{
		this.storeToFk = storeToFk;
	}

	public Date getActionDate()
	{
		return this.actionDate;
	}

	public void setActionDate(Date actionDate)
	{
		this.actionDate = actionDate;
	}

	public Long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Long getItemCount()
	{
		return this.itemCount;
	}

	public void setItemCount(Long itemCount)
	{
		this.itemCount = itemCount;
	}

	public BigDecimal getActionPrice()
	{
		return this.actionPrice;
	}

	public void setActionPrice(BigDecimal actionPrice)
	{
		this.actionPrice = actionPrice;
	}

	public String getActionNote()
	{
		return this.actionNote;
	}

	public void setActionNote(String actionNote)
	{
		this.actionNote = actionNote;
	}

	public Date getCreated()
	{
		return this.created;
	}

	public void setCreated(Date created)
	{
		this.created = created;
	}

}
