package hibernate_xml;

// default package
// Generated 31.07.2011 14:20:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PriceList generated by hbm2java
 */
public class PriceList implements java.io.Serializable
{

	private long priceList;
	private Long priceListStatusTypeFk;
	private Long defaultDiscountXtra;
	private Date dateFrom;
	private Date dateTo;
	private String note;
	private Long createdBy;
	private Date created;
	private Long updatedBy;
	private Date updated;

	public PriceList()
	{
	}

	public PriceList(long priceList)
	{
		this.priceList = priceList;
	}

	public PriceList(long priceList, Long priceListStatusTypeFk, Long defaultDiscountXtra,
			Date dateFrom, Date dateTo, String note, Long createdBy, Date created, Long updatedBy,
			Date updated)
	{
		this.priceList = priceList;
		this.priceListStatusTypeFk = priceListStatusTypeFk;
		this.defaultDiscountXtra = defaultDiscountXtra;
		this.dateFrom = dateFrom;
		this.dateTo = dateTo;
		this.note = note;
		this.createdBy = createdBy;
		this.created = created;
		this.updatedBy = updatedBy;
		this.updated = updated;
	}

	public long getPriceList()
	{
		return this.priceList;
	}

	public void setPriceList(long priceList)
	{
		this.priceList = priceList;
	}

	public Long getPriceListStatusTypeFk()
	{
		return this.priceListStatusTypeFk;
	}

	public void setPriceListStatusTypeFk(Long priceListStatusTypeFk)
	{
		this.priceListStatusTypeFk = priceListStatusTypeFk;
	}

	public Long getDefaultDiscountXtra()
	{
		return this.defaultDiscountXtra;
	}

	public void setDefaultDiscountXtra(Long defaultDiscountXtra)
	{
		this.defaultDiscountXtra = defaultDiscountXtra;
	}

	public Date getDateFrom()
	{
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom)
	{
		this.dateFrom = dateFrom;
	}

	public Date getDateTo()
	{
		return this.dateTo;
	}

	public void setDateTo(Date dateTo)
	{
		this.dateTo = dateTo;
	}

	public String getNote()
	{
		return this.note;
	}

	public void setNote(String note)
	{
		this.note = note;
	}

	public Long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getCreated()
	{
		return this.created;
	}

	public void setCreated(Date created)
	{
		this.created = created;
	}

	public Long getUpdatedBy()
	{
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy)
	{
		this.updatedBy = updatedBy;
	}

	public Date getUpdated()
	{
		return this.updated;
	}

	public void setUpdated(Date updated)
	{
		this.updated = updated;
	}

}
