package ttu.rakarh1.backend.model.data;
// Generated 31.07.2011 14:20:28 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable
{

	private long item;
	private Long unitTypeFk;
	private Long supplierEnterpriseFk;
	private Long itemTypeFk;
	private String name;
	private BigDecimal storePrice;
	private BigDecimal salePrice;
	private String producer;
	private String description;
	private String producerCode;
	private String singleItem;
	private Long upperItemFk;
	private String serialNo;
	private Date created;

	public Item()
	{
	}

	public Item(long item)
	{
		this.item = item;
	}

	public Item(long item, Long unitTypeFk, Long supplierEnterpriseFk, Long itemTypeFk,
			String name, BigDecimal storePrice, BigDecimal salePrice, String producer,
			String description, String producerCode, String singleItem, Long upperItemFk,
			String serialNo, Date created)
	{
		this.item = item;
		this.unitTypeFk = unitTypeFk;
		this.supplierEnterpriseFk = supplierEnterpriseFk;
		this.itemTypeFk = itemTypeFk;
		this.name = name;
		this.storePrice = storePrice;
		this.salePrice = salePrice;
		this.producer = producer;
		this.description = description;
		this.producerCode = producerCode;
		this.singleItem = singleItem;
		this.upperItemFk = upperItemFk;
		this.serialNo = serialNo;
		this.created = created;
	}

	public long getItem()
	{
		return this.item;
	}

	public void setItem(long item)
	{
		this.item = item;
	}

	public Long getUnitTypeFk()
	{
		return this.unitTypeFk;
	}

	public void setUnitTypeFk(Long unitTypeFk)
	{
		this.unitTypeFk = unitTypeFk;
	}

	public Long getSupplierEnterpriseFk()
	{
		return this.supplierEnterpriseFk;
	}

	public void setSupplierEnterpriseFk(Long supplierEnterpriseFk)
	{
		this.supplierEnterpriseFk = supplierEnterpriseFk;
	}

	public Long getItemTypeFk()
	{
		return this.itemTypeFk;
	}

	public void setItemTypeFk(Long itemTypeFk)
	{
		this.itemTypeFk = itemTypeFk;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public BigDecimal getStorePrice()
	{
		return this.storePrice;
	}

	public void setStorePrice(BigDecimal storePrice)
	{
		this.storePrice = storePrice;
	}

	public BigDecimal getSalePrice()
	{
		return this.salePrice;
	}

	public void setSalePrice(BigDecimal salePrice)
	{
		this.salePrice = salePrice;
	}

	public String getProducer()
	{
		return this.producer;
	}

	public void setProducer(String producer)
	{
		this.producer = producer;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public String getProducerCode()
	{
		return this.producerCode;
	}

	public void setProducerCode(String producerCode)
	{
		this.producerCode = producerCode;
	}

	public String getSingleItem()
	{
		return this.singleItem;
	}

	public void setSingleItem(String singleItem)
	{
		this.singleItem = singleItem;
	}

	public Long getUpperItemFk()
	{
		return this.upperItemFk;
	}

	public void setUpperItemFk(Long upperItemFk)
	{
		this.upperItemFk = upperItemFk;
	}

	public String getSerialNo()
	{
		return this.serialNo;
	}

	public void setSerialNo(String serialNo)
	{
		this.serialNo = serialNo;
	}

	public Date getCreated()
	{
		return this.created;
	}

	public void setCreated(Date created)
	{
		this.created = created;
	}

}
