package hibernate_xml;
// Generated 31.07.2011 14:20:28 by Hibernate Tools 3.4.0.CR1

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable
{

	private long customer;
	private Long subjectFk;
	private Long subjectTypeFk;

	public Customer()
	{
	}

	public Customer(long customer)
	{
		this.customer = customer;
	}

	public Customer(long customer, Long subjectFk, Long subjectTypeFk)
	{
		this.customer = customer;
		this.subjectFk = subjectFk;
		this.subjectTypeFk = subjectTypeFk;
	}

	public long getCustomer()
	{
		return this.customer;
	}

	public void setCustomer(long customer)
	{
		this.customer = customer;
	}

	public Long getSubjectFk()
	{
		return this.subjectFk;
	}

	public void setSubjectFk(Long subjectFk)
	{
		this.subjectFk = subjectFk;
	}

	public Long getSubjectTypeFk()
	{
		return this.subjectTypeFk;
	}

	public void setSubjectTypeFk(Long subjectTypeFk)
	{
		this.subjectTypeFk = subjectTypeFk;
	}

}
