package hibernate_xml;
// Generated 31.07.2011 14:20:28 by Hibernate Tools 3.4.0.CR1

/**
 * CustomerPriceList generated by hbm2java
 */
public class CustomerPriceList implements java.io.Serializable
{

	private long customerPriceList;
	private Long customerFk;
	private Long priceListFk;

	public CustomerPriceList()
	{
	}

	public CustomerPriceList(long customerPriceList)
	{
		this.customerPriceList = customerPriceList;
	}

	public CustomerPriceList(long customerPriceList, Long customerFk, Long priceListFk)
	{
		this.customerPriceList = customerPriceList;
		this.customerFk = customerFk;
		this.priceListFk = priceListFk;
	}

	public long getCustomerPriceList()
	{
		return this.customerPriceList;
	}

	public void setCustomerPriceList(long customerPriceList)
	{
		this.customerPriceList = customerPriceList;
	}

	public Long getCustomerFk()
	{
		return this.customerFk;
	}

	public void setCustomerFk(Long customerFk)
	{
		this.customerFk = customerFk;
	}

	public Long getPriceListFk()
	{
		return this.priceListFk;
	}

	public void setPriceListFk(Long priceListFk)
	{
		this.priceListFk = priceListFk;
	}

}
