package hibernate_xml;
// Generated 31.07.2011 14:20:28 by Hibernate Tools 3.4.0.CR1

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable
{

	private long employee;
	private Long personFk;
	private Long enterpriseFk;
	private Long structUnitFk;
	private String active;

	public Employee()
	{
	}

	public Employee(long employee)
	{
		this.employee = employee;
	}

	public Employee(long employee, Long personFk, Long enterpriseFk, Long structUnitFk,
			String active)
	{
		this.employee = employee;
		this.personFk = personFk;
		this.enterpriseFk = enterpriseFk;
		this.structUnitFk = structUnitFk;
		this.active = active;
	}

	public long getEmployee()
	{
		return this.employee;
	}

	public void setEmployee(long employee)
	{
		this.employee = employee;
	}

	public Long getPersonFk()
	{
		return this.personFk;
	}

	public void setPersonFk(Long personFk)
	{
		this.personFk = personFk;
	}

	public Long getEnterpriseFk()
	{
		return this.enterpriseFk;
	}

	public void setEnterpriseFk(Long enterpriseFk)
	{
		this.enterpriseFk = enterpriseFk;
	}

	public Long getStructUnitFk()
	{
		return this.structUnitFk;
	}

	public void setStructUnitFk(Long structUnitFk)
	{
		this.structUnitFk = structUnitFk;
	}

	public String getActive()
	{
		return this.active;
	}

	public void setActive(String active)
	{
		this.active = active;
	}

}
